/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./dashboard/templates/**/*.html",
    "./dashboard/static/**/*.js",
  ],
  safelist: [
    // Alert & notification categories
    "bg-success/10",
    "border-success/30",
    "text-success",
    "bg-danger/10",
    "border-danger/30",
    "text-danger",
    "bg-warning/10",
    "border-warning/30",
    "text-warning",
    "bg-info/10",
    "border-info/30",
    "text-info",
    // Flash badges
    "bg-primary/10",
    "border-primary/20",
    "border-primary/30",
    "text-primary",
    "bg-success/15",
    "border-success/20",
    "bg-danger/15",
    "bg-warning/15",
    "bg-info/15",
    // State toggles in JS
    "hidden",
    "-translate-x-full",
    "translate-x-0",
    "border-primary",
    "border-admin-accent",
    "bg-admin-accent/10",
    "bg-surface-container-low",
    "border-border-subtle",
    "icon-fill",
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#31394d",
        "on-secondary": "#00354a",
        "bg-card-hover": "#1E293B",
        "outline": "#89929b",
        "surface-container-lowest": "#060e20",
        "text-muted": "#64748B",
        "on-secondary-container": "#00374d",
        "on-tertiary": "#4b2800",
        "error-container": "#93000a",
        "inverse-surface": "#dae2fd",
        "primary": "#93ccff",
        "surface-container": "#171f33",
        "info": "#06B6D4",
        "primary-fixed": "#cce5ff",
        "on-primary-fixed": "#001d31",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#412200",
        "outline-variant": "#3f4850",
        "surface-container-high": "#222a3d",
        "danger": "#EF4444",
        "primary-container": "#3198dc",
        "surface-container-highest": "#2d3449",
        "border-subtle": "#1E293B",
        "surface-variant": "#2d3449",
        "surface": "#0b1326",
        "on-primary-container": "#002c47",
        "warning": "#F59E0B",
        "on-surface-variant": "#bfc7d2",
        "on-background": "#dae2fd",
        "text-secondary": "#94A3B8",
        "primary-fixed-dim": "#93ccff",
        "on-surface": "#dae2fd",
        "secondary-fixed-dim": "#7bd0ff",
        "error": "#ffb4ab",
        "surface-dim": "#0b1326",
        "bg-surface": "#0B0F19",
        "secondary-fixed": "#c4e7ff",
        "surface-container-low": "#131b2e",
        "bg-body": "#070B14",
        "text-primary": "#F8FAFC",
        "success": "#10B981",
        "admin-accent": "#EF4444",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "sidebar-width": "260px",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
