"""
HTML & Plain Text Email Renderer for CyberScout AI.
"""

from typing import Tuple

from src.notifier.base import ReportDigest
from src.notifier.exceptions import RenderError
from src.notifier.template_loader import TemplateLoader


class HTMLRenderer:
    """
    Renders ReportDigest model to HTML format and fallback plain text.
    """

    def __init__(self, template_loader: TemplateLoader = None):
        self.template_loader = template_loader or TemplateLoader()

    def render_report(self, digest: ReportDigest) -> Tuple[str, str]:
        """
        Renders HTML report and plain text fallback.

        Args:
            digest: Prepared ReportDigest object.

        Returns:
            Tuple of (html_content_str, plain_text_content_str).
        """
        try:
            # 1. Render HTML
            template = self.template_loader.load_template("report.html")
            html_content = template.render(
                date=digest.date,
                stats=digest.stats,
                categories=digest.categories,
            )

            # 2. Render Plain Text Fallback
            text_lines = [
                "==================================================",
                f"CYBERSCOUT AI ALERT - {digest.date}",
                "==================================================",
                f"Total Active Opportunities: {digest.total_opportunities}",
                f"High Priority Count: {digest.stats.get('high_priority_count', 0)}",
                f"Average Score: {digest.stats.get('average_score', 0.0)}",
                "--------------------------------------------------",
            ]

            for cat_name, items in digest.categories.items():
                if items:
                    text_lines.append(f"\n[{cat_name.upper()}]")
                    for opp in items:
                        text_lines.append(f"- {opp.title}")
                        text_lines.append(f"  URL: {opp.url}")
                        if opp.deadline:
                            text_lines.append(f"  Deadline: {opp.deadline}")
                        text_lines.append(f"  Score: {opp.score}")

            text_lines.append("\n==================================================")
            text_lines.append("Generated by CyberScout AI")
            plain_text = "\n".join(text_lines)

            return html_content, plain_text

        except Exception as e:
            raise RenderError(f"Failed to render email report: {e}", original_exception=e)
