"""
Collector Manager for CyberScout AI Collection Framework.

Orchestrates execution of SearchPlan tasks across collectors with exception isolation,
metrics tracking, and logging. Failure in one task or collector never stops the pipeline.
"""

import time
from typing import Dict, List, Optional

from src.collectors.base import BaseCollector
from src.collectors.context import CollectorContext
from src.collectors.factory import CollectorFactory
from src.collectors.metrics import CollectorMetrics
from src.collectors.registry import CollectorRegistry
from src.collectors.result import CollectorResult
from src.core.logging import get_logger
from src.intelligence.planner_models import SearchPlan, SearchTask

logger = get_logger(__name__)


class CollectorManager:
    """
    Central orchestrator for executing collection tasks safely and reliably.
    """

    def __init__(
        self,
        registry: Optional[CollectorRegistry] = None,
        factory: Optional[CollectorFactory] = None,
        context: Optional[CollectorContext] = None,
    ):
        self.registry = registry or CollectorRegistry()
        self.context = context or CollectorContext.create_default()
        self.factory = factory or CollectorFactory(registry=self.registry, context=self.context)
        self.metrics = CollectorMetrics()

    def execute_task(self, task: SearchTask, collector: Optional[BaseCollector] = None) -> CollectorResult:
        """
        Executes a single SearchTask with complete exception isolation.

        Args:
            task: Planned SearchTask instance.
            collector: Optional pre-instantiated BaseCollector.

        Returns:
            Standardized CollectorResult instance.
        """
        start_time = time.time()
        source_id = task.source_id

        if not collector:
            preferred_collector_name = task.metadata.get("preferred_collector", "GenericCollector")
            try:
                collector = self.factory.create_collector(preferred_collector_name, source_id=source_id)
            except Exception as e:
                logger.warning(f"Could not instantiate collector '{preferred_collector_name}': {e}. Using fallback.")

        if not collector:
            # Task fallback error result
            duration = time.time() - start_time
            return CollectorResult(
                source_id=source_id,
                status="failed",
                items=[],
                errors=[f"Failed to resolve collector for task '{task.task_id}'."],
                metrics=self.metrics.to_dict(),
                duration_seconds=duration,
            )

        try:
            logger.info(f"CollectorManager executing task '{task.task_id}' on source '{source_id}'...")
            result = collector.collect(task)
            duration = time.time() - start_time
            result.duration_seconds = duration
            result.metrics = self.metrics.to_dict()
            logger.info(f"Task '{task.task_id}' completed with status '{result.status}' ({result.item_count} items).")
            return result

        except Exception as e:
            duration = time.time() - start_time
            logger.error(f"Isolated exception executing collector task '{task.task_id}': {e}", exc_info=True)
            return CollectorResult(
                source_id=source_id,
                status="failed",
                items=[],
                errors=[f"Collector exception: {str(e)}"],
                metrics=self.metrics.to_dict(),
                duration_seconds=duration,
            )

    def execute_plan(self, plan: SearchPlan) -> List[CollectorResult]:
        """
        Executes all SearchTasks in a SearchPlan sequentially with error isolation.

        Args:
            plan: Master SearchPlan generated by Phase 2 SearchPlanner.

        Returns:
            List of CollectorResult instances.
        """
        start_time = time.time()
        results: List[CollectorResult] = []
        logger.info(f"CollectorManager starting plan execution ({plan.total_tasks} tasks)...")

        for task in plan.tasks:
            res = self.execute_task(task)
            results.append(res)

        total_duration = time.time() - start_time
        self.metrics.execution_duration_seconds = total_duration
        logger.info(f"CollectorManager completed plan execution ({len(results)} tasks) in {total_duration:.2f}s.")
        return results
