"""
Authoritative 75 Target Sources Catalog for CyberScout AI (Phase 2).

Defines the master registry of approved source families, access methods, trust tiers,
rate-limiting policies, compliance flags, and lifecycle statuses.
"""

from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

from src.models.enums import (
    AccessMethod,
    HealthStatus,
    OpportunityType,
    RobotsPolicy,
    SourceFamily,
    TermsReviewStatus,
    TrustTier,
)


@dataclass
class RateLimitPolicy:
    """Politeness and rate limiting configuration per source."""

    request_timeout: float = 15.0
    connect_timeout: float = 5.0
    read_timeout: float = 10.0
    retry_count: int = 3
    retry_backoff: float = 1.5
    min_request_interval_seconds: float = 1.0
    max_concurrency: int = 2
    user_agent: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class SourceDefinition:
    """Canonical definition of an opportunity source."""

    source_id: str
    name: str
    canonical_url: str
    organization: str
    country_scope: str
    language: str
    source_family: str
    opportunity_types: List[str]
    collector_type: str
    access_method: str
    trust_tier: str
    requires_auth: bool = False
    rate_limit_policy: RateLimitPolicy = field(default_factory=RateLimitPolicy)
    robots_policy: str = RobotsPolicy.RESPECT.value
    terms_review_status: str = TermsReviewStatus.APPROVED.value
    parser_version: str = "1.0.0"
    health_status: str = HealthStatus.HEALTHY.value
    status: str = "REGISTERED"  # REGISTERED, CONFIGURED, IMPLEMENTED, VALIDATED, ENABLED, DISABLED, MANUAL_REVIEW, UNSUPPORTED
    enabled: bool = True
    last_success_at: Optional[str] = None
    last_failure_at: Optional[str] = None
    last_checked_at: Optional[str] = None
    last_item_count: int = 0
    last_new_item_count: int = 0
    last_updated_item_count: int = 0
    failure_count: int = 0
    success_count: int = 0
    latency: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["rate_limit_policy"] = self.rate_limit_policy.to_dict()
        return data


# ==============================================================================
# AUTHORITATIVE 75 SOURCE CATALOG
# ==============================================================================

AUTHORITATIVE_SOURCES: Dict[str, SourceDefinition] = {
    # --------------------------------------------------------------------------
    # INDIA — INTERNSHIPS / CAREERS (1-15)
    # --------------------------------------------------------------------------
    "aicte_internships": SourceDefinition(
        source_id="aicte_internships",
        name="AICTE National Internship Portal",
        canonical_url="https://internship.aicte-india.org/",
        organization="All India Council for Technical Education (AICTE)",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "ncs_india": SourceDefinition(
        source_id="ncs_india",
        name="National Career Service (NCS)",
        canonical_url="https://www.ncs.gov.in/",
        organization="Ministry of Labour and Employment, Govt. of India",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "aicte_placements": SourceDefinition(
        source_id="aicte_placements",
        name="AICTE Placement Portal",
        canonical_url="https://placement.aicte-india.org/",
        organization="All India Council for Technical Education (AICTE)",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "internshala": SourceDefinition(
        source_id="internshala",
        name="Internshala",
        canonical_url="https://internshala.com/",
        organization="Internshala",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="html_extraction",
        access_method=AccessMethod.HTML_EXTRACTION.value,
        trust_tier=TrustTier.TIER_2.value,
        terms_review_status=TermsReviewStatus.RESTRICTED.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "unstop": SourceDefinition(
        source_id="unstop",
        name="Unstop",
        canonical_url="https://unstop.com/",
        organization="Unstop (FLAM)",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.HACKATHON.value, OpportunityType.COMPETITION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "freshersworld": SourceDefinition(
        source_id="freshersworld",
        name="Freshersworld",
        canonical_url="https://www.freshersworld.com/",
        organization="TeamLease / Freshersworld",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "apna": SourceDefinition(
        source_id="apna",
        name="Apna",
        canonical_url="https://apna.co/",
        organization="Apna Communities Inc.",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "foundit": SourceDefinition(
        source_id="foundit",
        name="Foundit",
        canonical_url="https://www.foundit.in/",
        organization="foundit (formerly Monster India)",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "cutshort": SourceDefinition(
        source_id="cutshort",
        name="Cutshort",
        canonical_url="https://cutshort.io/",
        organization="Cutshort Technologies",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "wellfound": SourceDefinition(
        source_id="wellfound",
        name="Wellfound",
        canonical_url="https://wellfound.com/",
        organization="Wellfound (formerly AngelList Talent)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "superset": SourceDefinition(
        source_id="superset",
        name="Superset",
        canonical_url="https://joinsuperset.com/",
        organization="Superset Campus Placements",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="unsupported",
        access_method=AccessMethod.UNSUPPORTED.value,
        requires_auth=True,
        trust_tier=TrustTier.TIER_2.value,
        terms_review_status=TermsReviewStatus.RESTRICTED.value,
        status="UNSUPPORTED",
        enabled=False,
    ),
    "naukri": SourceDefinition(
        source_id="naukri",
        name="Naukri",
        canonical_url="https://www.naukri.com/",
        organization="Info Edge India Ltd.",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "linkedin_jobs": SourceDefinition(
        source_id="linkedin_jobs",
        name="LinkedIn Jobs",
        canonical_url="https://www.linkedin.com/jobs/",
        organization="Microsoft / LinkedIn",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.JOB.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        terms_review_status=TermsReviewStatus.RESTRICTED.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "indeed_india": SourceDefinition(
        source_id="indeed_india",
        name="Indeed India",
        canonical_url="https://in.indeed.com/",
        organization="Indeed / Recruit Holdings",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.JOB.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "letsintern": SourceDefinition(
        source_id="letsintern",
        name="LetsIntern",
        canonical_url="https://www.letsintern.com/",
        organization="LetsIntern",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.INDIAN_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_3.value,
        status="CONFIGURED",
        enabled=True,
    ),

    # --------------------------------------------------------------------------
    # GLOBAL INTERNSHIPS / EARLY CAREER (16-25)
    # --------------------------------------------------------------------------
    "handshake": SourceDefinition(
        source_id="handshake",
        name="Handshake",
        canonical_url="https://joinhandshake.com/",
        organization="Stryder Corp. (Handshake)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        requires_auth=True,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "wayup": SourceDefinition(
        source_id="wayup",
        name="WayUp",
        canonical_url="https://www.wayup.com/",
        organization="Yello / WayUp",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "ripplematch": SourceDefinition(
        source_id="ripplematch",
        name="RippleMatch",
        canonical_url="https://ripplematch.com/",
        organization="RippleMatch Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        requires_auth=True,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "forage": SourceDefinition(
        source_id="forage",
        name="Forage",
        canonical_url="https://www.theforage.com/",
        organization="Forage / InsideSherpa",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.COURSE.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "gradcracker": SourceDefinition(
        source_id="gradcracker",
        name="Gradcracker",
        canonical_url="https://www.gradcracker.com/",
        organization="Gradcracker UK",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "prosple": SourceDefinition(
        source_id="prosple",
        name="Prosple",
        canonical_url="https://prosple.com/",
        organization="Prosple Pty Ltd",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value, OpportunityType.JOB.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "euraxess": SourceDefinition(
        source_id="euraxess",
        name="Euraxess",
        canonical_url="https://euraxess.ec.europa.eu/",
        organization="European Commission",
        country_scope="EU",
        language="en",
        source_family=SourceFamily.RESEARCH.value,
        opportunity_types=[OpportunityType.RESEARCH.value, OpportunityType.FELLOWSHIP.value, OpportunityType.JOB.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "academic_positions": SourceDefinition(
        source_id="academic_positions",
        name="Academic Positions",
        canonical_url="https://academicpositions.com/",
        organization="Academic Positions Sweden AB",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.RESEARCH.value,
        opportunity_types=[OpportunityType.RESEARCH.value, OpportunityType.FELLOWSHIP.value, OpportunityType.JOB.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "chegg_internships": SourceDefinition(
        source_id="chegg_internships",
        name="Chegg Internships",
        canonical_url="https://www.internships.com/",
        organization="Chegg Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.GLOBAL_INTERNSHIP.value,
        opportunity_types=[OpportunityType.INTERNSHIP.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),
    "glassdoor": SourceDefinition(
        source_id="glassdoor",
        name="Glassdoor",
        canonical_url="https://www.glassdoor.com/",
        organization="Glassdoor LLC / Recruit",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.JOB.value,
        opportunity_types=[OpportunityType.JOB.value, OpportunityType.INTERNSHIP.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_2.value,
        terms_review_status=TermsReviewStatus.RESTRICTED.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),

    # --------------------------------------------------------------------------
    # HACKATHONS / DEVELOPER COMPETITIONS (26-35)
    # --------------------------------------------------------------------------
    "devpost": SourceDefinition(
        source_id="devpost",
        name="Devpost",
        canonical_url="https://devpost.com/",
        organization="Devpost Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value, OpportunityType.COMPETITION.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "hackerearth": SourceDefinition(
        source_id="hackerearth",
        name="HackerEarth",
        canonical_url="https://www.hackerearth.com/challenges/",
        organization="HackerEarth Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value, OpportunityType.COMPETITION.value, OpportunityType.JOB.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "mlh": SourceDefinition(
        source_id="mlh",
        name="Major League Hacking (MLH)",
        canonical_url="https://mlh.io/",
        organization="Major League Hacking",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "devfolio": SourceDefinition(
        source_id="devfolio",
        name="Devfolio",
        canonical_url="https://devfolio.co/",
        organization="Devfolio (Devfolio Labs)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "hackernoon_hackathons": SourceDefinition(
        source_id="hackernoon_hackathons",
        name="HackerNoon Hackathons",
        canonical_url="https://hackernoon.com/",
        organization="HackerNoon",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value, OpportunityType.COMPETITION.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "hack2skill": SourceDefinition(
        source_id="hack2skill",
        name="Hack2Skill",
        canonical_url="https://hack2skill.com/",
        organization="Hack2Skill Community",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value, OpportunityType.COMPETITION.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "hackathon_com": SourceDefinition(
        source_id="hackathon_com",
        name="Hackathon.com",
        canonical_url="https://www.hackathon.com/",
        organization="Hackathon.com",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.HACKATHON.value,
        opportunity_types=[OpportunityType.HACKATHON.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_3.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "kaggle": SourceDefinition(
        source_id="kaggle",
        name="Kaggle",
        canonical_url="https://www.kaggle.com/competitions",
        organization="Google / Kaggle",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COMPETITION.value,
        opportunity_types=[OpportunityType.COMPETITION.value, OpportunityType.CHALLENGE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "topcoder": SourceDefinition(
        source_id="topcoder",
        name="Topcoder",
        canonical_url="https://www.topcoder.com/challenges",
        organization="Wipro / Topcoder",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COMPETITION.value,
        opportunity_types=[OpportunityType.COMPETITION.value, OpportunityType.CHALLENGE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "challenge_gov": SourceDefinition(
        source_id="challenge_gov",
        name="Challenge.gov",
        canonical_url="https://www.challenge.gov/",
        organization="General Services Administration (GSA), US Govt",
        country_scope="US",
        language="en",
        source_family=SourceFamily.CHALLENGE.value,
        opportunity_types=[OpportunityType.CHALLENGE.value, OpportunityType.COMPETITION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),

    # --------------------------------------------------------------------------
    # CYBERSECURITY / CTF (36-45)
    # --------------------------------------------------------------------------
    "ctftime": SourceDefinition(
        source_id="ctftime",
        name="CTFtime",
        canonical_url="https://ctftime.org/",
        organization="CTFtime Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CTF.value,
        opportunity_types=[OpportunityType.CTF.value, OpportunityType.COMPETITION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "picoctf": SourceDefinition(
        source_id="picoctf",
        name="picoCTF",
        canonical_url="https://picoctf.org/",
        organization="Carnegie Mellon University",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CTF.value,
        opportunity_types=[OpportunityType.CTF.value, OpportunityType.COURSE.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "tryhackme": SourceDefinition(
        source_id="tryhackme",
        name="TryHackMe",
        canonical_url="https://tryhackme.com/",
        organization="TryHackMe Ltd.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CYBERSECURITY.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CHALLENGE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "hackthebox": SourceDefinition(
        source_id="hackthebox",
        name="Hack The Box",
        canonical_url="https://www.hackthebox.com/",
        organization="Hack The Box",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CYBERSECURITY.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CTF.value, OpportunityType.CHALLENGE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "overthewire": SourceDefinition(
        source_id="overthewire",
        name="OverTheWire",
        canonical_url="https://overthewire.org/wargames/",
        organization="OverTheWire Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CYBERSECURITY.value,
        opportunity_types=[OpportunityType.CHALLENGE.value],
        collector_type="html_extraction",
        access_method=AccessMethod.HTML_EXTRACTION.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "cyberdefenders": SourceDefinition(
        source_id="cyberdefenders",
        name="CyberDefenders",
        canonical_url="https://cyberdefenders.org/",
        organization="CyberDefenders",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CYBERSECURITY.value,
        opportunity_types=[OpportunityType.CHALLENGE.value, OpportunityType.COURSE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "root_me": SourceDefinition(
        source_id="root_me",
        name="Root-Me",
        canonical_url="https://www.root-me.org/",
        organization="Root-Me Pro",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.CYBERSECURITY.value,
        opportunity_types=[OpportunityType.CTF.value, OpportunityType.CHALLENGE.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "portswigger_academy": SourceDefinition(
        source_id="portswigger_academy",
        name="PortSwigger Web Security Academy",
        canonical_url="https://portswigger.net/web-security",
        organization="PortSwigger Ltd.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "owasp": SourceDefinition(
        source_id="owasp",
        name="OWASP",
        canonical_url="https://owasp.org/",
        organization="Open Web Application Security Project (OWASP)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value, OpportunityType.CONFERENCE.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "sans_cyber_aces": SourceDefinition(
        source_id="sans_cyber_aces",
        name="SANS Cyber Aces",
        canonical_url="https://www.cyberaces.org/",
        organization="SANS Institute",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),

    # --------------------------------------------------------------------------
    # BUG BOUNTY / SECURITY RESEARCH (46-52)
    # --------------------------------------------------------------------------
    "hackerone": SourceDefinition(
        source_id="hackerone",
        name="HackerOne",
        canonical_url="https://hackerone.com/directory/programs",
        organization="HackerOne Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "bugcrowd": SourceDefinition(
        source_id="bugcrowd",
        name="Bugcrowd",
        canonical_url="https://bugcrowd.com/programs",
        organization="Bugcrowd Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "intigriti": SourceDefinition(
        source_id="intigriti",
        name="Intigriti",
        canonical_url="https://www.intigriti.com/",
        organization="Intigriti NV",
        country_scope="EU",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "yeswehack": SourceDefinition(
        source_id="yeswehack",
        name="YesWeHack",
        canonical_url="https://www.yeswehack.com/",
        organization="YesWeHack SAS",
        country_scope="EU",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "hackenproof": SourceDefinition(
        source_id="hackenproof",
        name="HackenProof",
        canonical_url="https://hackenproof.com/",
        organization="HackenProof",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "openbugbounty": SourceDefinition(
        source_id="openbugbounty",
        name="Open Bug Bounty",
        canonical_url="https://www.openbugbounty.org/",
        organization="Open Bug Bounty Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value, OpportunityType.SECURITY_RESEARCH.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "federacy": SourceDefinition(
        source_id="federacy",
        name="Federacy",
        canonical_url="https://www.federacy.com/",
        organization="Federacy Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.BUG_BOUNTY.value,
        opportunity_types=[OpportunityType.BUG_BOUNTY.value],
        collector_type="manual_curated",
        access_method=AccessMethod.MANUAL_CURATED.value,
        trust_tier=TrustTier.TIER_3.value,
        status="MANUAL_REVIEW",
        enabled=False,
    ),

    # --------------------------------------------------------------------------
    # LEARNING / COURSES (53-67)
    # --------------------------------------------------------------------------
    "microsoft_learn": SourceDefinition(
        source_id="microsoft_learn",
        name="Microsoft Learn",
        canonical_url="https://learn.microsoft.com/",
        organization="Microsoft Corporation",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "cisco_skills_for_all": SourceDefinition(
        source_id="cisco_skills_for_all",
        name="Cisco Skills for All",
        canonical_url="https://skillsforall.com/",
        organization="Cisco Systems Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "ibm_skillsbuild": SourceDefinition(
        source_id="ibm_skillsbuild",
        name="IBM SkillsBuild",
        canonical_url="https://skillsbuild.org/",
        organization="International Business Machines (IBM)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "nasscom_futureskills": SourceDefinition(
        source_id="nasscom_futureskills",
        name="NASSCOM FutureSkills Prime",
        canonical_url="https://futureskillsprime.in/",
        organization="NASSCOM & Ministry of Electronics and IT (MeitY)",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "freecodecamp": SourceDefinition(
        source_id="freecodecamp",
        name="freeCodeCamp",
        canonical_url="https://www.freecodecamp.org/",
        organization="freeCodeCamp Foundation",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "khan_academy": SourceDefinition(
        source_id="khan_academy",
        name="Khan Academy",
        canonical_url="https://www.khanacademy.org/",
        organization="Khan Academy",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "edx": SourceDefinition(
        source_id="edx",
        name="edX",
        canonical_url="https://www.edx.org/",
        organization="edX / 2U Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "coursera": SourceDefinition(
        source_id="coursera",
        name="Coursera",
        canonical_url="https://www.coursera.org/",
        organization="Coursera Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "mit_ocw": SourceDefinition(
        source_id="mit_ocw",
        name="MIT OpenCourseWare",
        canonical_url="https://ocw.mit.edu/",
        organization="Massachusetts Institute of Technology (MIT)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "harvard_online": SourceDefinition(
        source_id="harvard_online",
        name="Harvard Online",
        canonical_url="https://www.harvardonline.harvard.edu/",
        organization="Harvard University",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "openlearn": SourceDefinition(
        source_id="openlearn",
        name="OpenLearn",
        canonical_url="https://www.open.edu/openlearn/",
        organization="The Open University (UK)",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "saylor_academy": SourceDefinition(
        source_id="saylor_academy",
        name="Saylor Academy",
        canonical_url="https://www.saylor.org/",
        organization="Saylor Academy",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "class_central": SourceDefinition(
        source_id="class_central",
        name="Class Central",
        canonical_url="https://www.classcentral.com/",
        organization="Class Central",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_3.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "odin_project": SourceDefinition(
        source_id="odin_project",
        name="The Odin Project",
        canonical_url="https://www.theodinproject.com/",
        organization="The Odin Project",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.OPEN_SOURCE.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "cs50_harvard": SourceDefinition(
        source_id="cs50_harvard",
        name="CS50 / Harvard",
        canonical_url="https://cs50.harvard.edu/",
        organization="Harvard University",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.COURSE.value,
        opportunity_types=[OpportunityType.COURSE.value, OpportunityType.CERTIFICATION.value],
        collector_type="official_feed",
        access_method=AccessMethod.OFFICIAL_FEED.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),

    # --------------------------------------------------------------------------
    # OPEN SOURCE / DEVELOPER OPPORTUNITIES (68-75)
    # --------------------------------------------------------------------------
    "github": SourceDefinition(
        source_id="github",
        name="GitHub",
        canonical_url="https://github.com/",
        organization="GitHub Inc. / Microsoft",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "gitlab": SourceDefinition(
        source_id="gitlab",
        name="GitLab",
        canonical_url="https://gitlab.com/",
        organization="GitLab Inc.",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "good_first_issue": SourceDefinition(
        source_id="good_first_issue",
        name="Good First Issue",
        canonical_url="https://goodfirstissue.dev/",
        organization="Good First Issue Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "up_for_grabs": SourceDefinition(
        source_id="up_for_grabs",
        name="Up For Grabs",
        canonical_url="https://up-for-grabs.net/",
        organization="Up For Grabs Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_2.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "codetriage": SourceDefinition(
        source_id="codetriage",
        name="CodeTriage",
        canonical_url="https://www.codetriage.com/",
        organization="CodeTriage Community",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value],
        collector_type="rss",
        access_method=AccessMethod.RSS.value,
        trust_tier=TrustTier.TIER_2.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "c4gt": SourceDefinition(
        source_id="c4gt",
        name="Code for GovTech (C4GT)",
        canonical_url="https://www.codeforgovtech.in/",
        organization="Samagra & C4GT Community",
        country_scope="IN",
        language="en-IN",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value, OpportunityType.FELLOWSHIP.value, OpportunityType.INTERNSHIP.value],
        collector_type="structured_public_endpoint",
        access_method=AccessMethod.STRUCTURED_ENDPOINT.value,
        trust_tier=TrustTier.TIER_1.value,
        status="CONFIGURED",
        enabled=True,
    ),
    "outreachy": SourceDefinition(
        source_id="outreachy",
        name="Outreachy",
        canonical_url="https://www.outreachy.org/",
        organization="Software Freedom Conservancy",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value, OpportunityType.INTERNSHIP.value, OpportunityType.FELLOWSHIP.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
    "google_summer_of_code": SourceDefinition(
        source_id="google_summer_of_code",
        name="Google Summer of Code",
        canonical_url="https://summerofcode.withgoogle.com/",
        organization="Google LLC",
        country_scope="GLOBAL",
        language="en",
        source_family=SourceFamily.OPEN_SOURCE.value,
        opportunity_types=[OpportunityType.OPEN_SOURCE.value, OpportunityType.INTERNSHIP.value, OpportunityType.FELLOWSHIP.value],
        collector_type="api",
        access_method=AccessMethod.API.value,
        trust_tier=TrustTier.TIER_1.value,
        status="IMPLEMENTED",
        enabled=True,
    ),
}

TARGET_75_SOURCE_IDS: List[str] = list(AUTHORITATIVE_SOURCES.keys())


def get_source_definition(source_id: str) -> Optional[SourceDefinition]:
    """Retrieves a source definition by ID from the authoritative catalog."""
    return AUTHORITATIVE_SOURCES.get(source_id.lower().strip())

